FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./monitoring.py .
COPY ./src src/
COPY ./config_ml.py src/model/

EXPOSE 8001
CMD ["python", "monitoring.py"]
